import {build} from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const here=path.dirname(fileURLToPath(import.meta.url));
const output=path.resolve(here,'../../Sources/PicShotFormulaRenderHelper/FormulaRenderResources');
const mathjax=JSON.parse(await fs.readFile(path.join(here,'node_modules/mathjax-full/package.json'),'utf8'));
if (mathjax.version!=='3.2.2' || mathjax.license!=='Apache-2.0') throw Error('Unexpected MathJax provenance');
const result=await build({entryPoints:[path.join(here,'FormulaRender-entry.js')],bundle:true,minify:true,platform:'browser',format:'iife',globalName:'FormulaRenderRuntime',target:'safari17',write:false,legalComments:'none',metafile:true});
if (Object.keys(result.metafile.inputs).some(p=>!p.includes('node_modules/mathjax-full/') && !p.endsWith('FormulaRender-entry.js'))) throw Error('Unexpected runtime dependency');
if (result.outputFiles[0].contents.length>2*1024*1024) throw Error('Runtime exceeds 2 MiB resource limit');
await fs.mkdir(output,{recursive:true});
const data=result.outputFiles[0].contents;
await fs.writeFile(path.join(output,'FormulaRenderRuntime.js'),data);
await fs.copyFile(path.join(here,'node_modules/mathjax-full/LICENSE'),path.join(output,'FormulaRender-MathJax-LICENSE.txt'));
await fs.writeFile(path.join(output,'FormulaRenderRuntime.sha256'),createHash('sha256').update(data).digest('hex')+'\n');
await fs.writeFile(path.join(output,'FormulaRenderRuntime-provenance.json'),JSON.stringify({engine:'mathjax-full',version:'3.2.2',license:'Apache-2.0',source:'https://github.com/mathjax/MathJax-src/tree/3.2.2',sourceCommit:'ad8f5c21cb810236551da8c6512ba733e67357ee',tarball:'https://registry.npmjs.org/mathjax-full/-/mathjax-full-3.2.2.tgz',integrity:'sha512-+LfG9Fik+OuI8SLwsiR02IVdjcnRCy5MufYLi0C3TdMT56L/pjB0alMVGgoWJF8pN9Rc7FESycZB9BMNWIid5w==',packages:['base','ams'],font:'MathJax TeX SVG paths',bundler:'esbuild 0.25.12',bytes:data.length},null,2)+'\n');
console.log(`Generated ${data.length} byte local-only renderer`);
