import AppKit
import AVFoundation
import CoreImage
import Foundation
import Darwin
import ImageIO
import ScreenCaptureKit
import UniformTypeIdentifiers

/// Explicit installed-app smoke only. Original synthetic pixels exercise the
/// production compositor/writer and overlay-controller methods without opening
/// a window, starting capture hardware, requesting TCC or posting input events.
@MainActor
enum RecordingCompositionSmokeFixture {
    struct Profile: Equatable, Sendable {
        let name: String
        let width: Int
        let height: Int
        let measuredCycles: Int
        let warmupCycles = 1
        let frameRate = 10
        let encodedFrames = 7
        let cameraWidth = 160
        let cameraHeight = 120
        var duration: Double { Double(encodedFrames) / Double(frameRate) }
        static let installedSmoke = Profile(name: "installed-recording-composition", width: 640, height: 360, measuredCycles: 3)
        static let quickTest = Profile(name: "unit-test-recording-composition", width: 320, height: 180, measuredCycles: 2)
    }

    /// Retains exactly recording-composition.mp4, recording-composition.png and
    /// recording-composition.json in the caller's evidence directory. Other
    /// evidence already in that directory is untouched. JSON is also written on
    /// failure when possible; the launcher owns the hard process timeout.
    static func verify(evidenceDirectory: URL, profile: Profile = .installedSmoke, traceEnabled: Bool = false) async throws -> [String: Any] {
        try require(evidenceDirectory.isFileURL, "Evidence must be a local file directory")
        try require(profile == .installedSmoke || profile == .quickTest, "Unknown bounded recording smoke profile")
        let files = FileManager.default
        try files.createDirectory(at: evidenceDirectory, withIntermediateDirectories: true)
        let reportURL = evidenceDirectory.appendingPathComponent("recording-composition.json")
        for witness in ["recording-composition.mp4", "recording-composition.png"] {
            try require(!files.fileExists(atPath: evidenceDirectory.appendingPathComponent(witness).path),
                        "Refusing to replace existing recording witness: \(witness)")
        }
        if traceEnabled {
            try require(!files.fileExists(atPath: evidenceDirectory.appendingPathComponent("recording-composition-trace.json").path),
                        "Refusing to replace an existing recording diagnostic trace")
        }
        let root = files.temporaryDirectory.appendingPathComponent("PicShot-Recording-Composition-" + UUID().uuidString, isDirectory: true)
        try files.createDirectory(at: root, withIntermediateDirectories: false, attributes: [.posixPermissions: 0o700])
        defer { try? files.removeItem(at: root) }
        let started = ProcessInfo.processInfo.systemUptime
        let deadline = started + 120
        let trace = traceEnabled ? RecordingCompositionSmokeTrace(directory: evidenceDirectory) : nil
        trace?.record("fixture.begin", details: ["profile": profile.name, "cooperativeDeadlineSeconds": 120])
        var report: [String: Any] = [
            "status": "running", "profile": profile.name,
            "sourceCommit": Bundle.main.infoDictionary?["PicShotSourceCommit"] as? String ?? "unknown",
            "operatingSystem": ProcessInfo.processInfo.operatingSystemVersionString,
            "sourceProvenance": "original synthetic two-band desktop with gray/color ramps and four-quadrant/solid camera pixels generated by this fixture",
            "screenCaptureStarted": false, "cameraCaptureStarted": false, "microphoneStarted": false,
            "permissionRequested": false, "windowsCreated": 0, "inputEventsPosted": 0, "externalDownloads": false,
            "width": profile.width, "height": profile.height, "cameraWidth": profile.cameraWidth,
            "cameraHeight": profile.cameraHeight, "frameRate": profile.frameRate,
            "encodedFramesPerCycle": profile.encodedFrames, "activeDurationSeconds": profile.duration,
            "removedPauseSeconds": 1.0, "warmupCycles": profile.warmupCycles, "measuredCycles": profile.measuredCycles,
            "syntheticInputColorSpace": "sRGB", "compositorInputToWriterColorSpace": "sRGB", "encodedOutputColorSpace": "ITU-R BT.709",
            "rampValidationColorSpace": "sRGB", "rampMaximumChannelError": 12,
            "overlayRefreshScheduling": "deterministic clock; manually invoke the production timer handler on its encoder queue; timer scheduling itself is not tested",
            "controllerScope": "direct production overlay-controller drag/resize/crop/pen/eraser/clear methods; no window, screen coordinates, mouse event delivery or camera provider is exercised",
            "memoryScope": "main-process RSS and physical footprint only; excludes GPU and AVFoundation service processes",
            "peakScope": "sampled cycle maxima during composition, encoding, decoding and cleanup; 50 ms timer plus explicit boundaries, not kernel lifetime peaks",
            "cleanupScope": "weak-reference release of writer/compositor/state/overlay controller plus production writer retained-frame count and latest camera slot; internal codec/pixel-pool allocations are not individually counted",
            "resourceScope": "short fixed-resolution repeated pipeline cycles after one warm-up; observational regression evidence, not zero-leak, long-recording, maximum-resolution or real-device acceptance",
            "sampleIntervalSeconds": GIFResourceMemorySampler.interval,
            "maximumMovieBytes": 4 * 1_024 * 1_024, "maximumPNGBytes": 4 * 1_024 * 1_024,
            "productionWriterFileLimitBytes": 16 * 1_024 * 1_024,
            "diskScope": "one temporary MP4 at a time plus one retained MP4/decoded PNG witness; no source media is written",
            "cooperativeDeadlineSeconds": 120, "temporaryDirectoryRemoved": false,
            "nativeCameraAndTCCAcceptance": "not exercised", "screenWindowExclusionAcceptance": "not exercised"
        ]
        do {
            report["phase"] = "warmup"
            trace?.cycle = "warmup"
            let warmup = try await cycle(root: root, profile: profile, witnessDirectory: nil, deadline: deadline, trace: trace)
            report["warmup"] = warmup.report
            let baseline = GIFResourceMemoryReading.current()
            try require(baseline.residentBytes != nil, "Main-process RSS is unavailable")
            report["baselineAfterWarmup"] = try object(baseline)
            var runs: [[String: Any]] = [], settled: [GIFResourceMemoryReading] = [], peaks: [GIFResourceMemoryStatistics] = []
            for index in 0..<profile.measuredCycles {
                report["phase"] = "measured-cycle-\(index + 1)"
                trace?.cycle = "measured-cycle-\(index + 1)"
                try checkDeadline(deadline)
                let result = try await cycle(root: root, profile: profile,
                    witnessDirectory: index == 0 ? evidenceDirectory : nil, deadline: deadline, trace: trace)
                runs.append(result.report); settled.append(result.settled); peaks.append(result.memory)
                report["cycles"] = runs
                try write(report, to: reportURL)
            }
            // Reuse the existing, independently tested process-memory sampler and
            // generous 384/96/32 MiB observational envelope without changing it.
            let resident = GIFResourceAssessment(baseline: baseline.residentBytes,
                settled: settled.map(\.residentBytes), peaks: peaks.map(\.peakResidentBytes))
            let footprint = GIFResourceAssessment(baseline: baseline.physicalFootprintBytes,
                settled: settled.map(\.physicalFootprintBytes), peaks: peaks.map(\.peakPhysicalFootprintBytes))
            report["residentAssessment"] = try object(resident)
            report["physicalFootprintAssessment"] = try object(footprint)
            report["settledAfterCycles"] = try settled.map { try object($0) }
            report["controllerCreationCount"] = profile.measuredCycles + profile.warmupCycles
            report["controllerReleaseCount"] = profile.measuredCycles + profile.warmupCycles
            report["pipelineCreationCount"] = profile.measuredCycles + profile.warmupCycles
            report["pipelineReleaseCount"] = profile.measuredCycles + profile.warmupCycles
            report["writerRetainedFrameReferencesAfterEachFinish"] = 0
            report["cameraSlotsAfterEachCleanup"] = 0
            report["witnessMovie"] = "recording-composition.mp4"
            report["witnessPNG"] = "recording-composition.png"
            report["phase"] = "owned-root-cleanup"
            report["completedMeasuredCycles"] = runs.count
            try write(report, to: reportURL)
            report["rootCleanupDisposition"] = try removeOwnedEmptyRoot(root)
            try require(ownedDirectoryIsAbsent(root), "Temporary recording directory was not removed")
            report["temporaryDirectoryRemoved"] = true
            report["elapsedSeconds"] = ProcessInfo.processInfo.systemUptime - started
            let passed = resident.withinEnvelope == true && (footprint.withinEnvelope ?? true)
            report["status"] = passed ? "passed" : "failed"
            trace?.record("fixture.end", details: ["status": passed ? "passed" : "failed"])
            if let trace { report["diagnostics"] = trace.summary }
            try write(report, to: reportURL)
            try require(passed, "Recording composition memory observations exceeded the fixed smoke envelope; inspect recording-composition.json")
            return report
        } catch {
            trace?.record("fixture.failure", details: ["error": String(error.localizedDescription.prefix(512)), "taskCancelled": Task.isCancelled])
            trace?.record("root-cleanup.begin")
            try? files.removeItem(at: root)
            trace?.record("root-cleanup.end", details: ["directoryAbsent": ownedDirectoryIsAbsent(root)])
            if let trace { report["diagnostics"] = trace.summary }
            report["temporaryDirectoryRemoved"] = ownedDirectoryIsAbsent(root)
            report["status"] = "failed"; report["error"] = error.localizedDescription
            report["elapsedSeconds"] = ProcessInfo.processInfo.systemUptime - started
            try? write(report, to: reportURL)
            throw error
        }
    }

    private struct CycleResult {
        let report: [String: Any]
        let settled: GIFResourceMemoryReading
        let memory: GIFResourceMemoryStatistics
    }

    private static func cycle(root: URL, profile: Profile, witnessDirectory: URL?, deadline: Double,
                              trace: RecordingCompositionSmokeTrace?) async throws -> CycleResult {
        let directory = root.appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
        defer { try? FileManager.default.removeItem(at: directory) }
        let sampler = GIFResourceMemorySampler()
        defer { sampler.stop() }
        let probe = RecordingCompositionSmokeReleaseProbe()
        let started = ProcessInfo.processInfo.systemUptime
        trace?.record("cycle.begin")
        var report = try await pipeline(directory: directory, profile: profile, witnessDirectory: witnessDirectory,
                                        sampler: sampler, probe: probe, deadline: deadline, trace: trace)
        // Awaiting an async method's return may briefly overlap the encoder's
        // final completion closure. Verify weak release after a bounded settle.
        let releaseDeadline = min(deadline, ProcessInfo.processInfo.systemUptime + 3)
        trace?.record("weak-release.begin", details: ["limitSeconds": 3, "liveObjects": probe.liveObjects])
        do {
            while probe.liveObjectCount != 0 {
                try checkDeadline(releaseDeadline)
                try await Task.sleep(nanoseconds: 20_000_000)
            }
        } catch {
            trace?.record("weak-release.failure", details: ["error": String(error.localizedDescription.prefix(512)), "liveObjects": probe.liveObjects])
            throw error
        }
        trace?.record("weak-release.end", details: ["liveObjects": probe.liveObjects])
        report["releasedObjects"] = ["writer": true, "compositor": true, "state": true, "overlayController": true]
        report["liveTrackedObjectsAfterRelease"] = probe.liveObjectCount
        trace?.record("cycle-cleanup.begin")
        report["directoryCleanupDisposition"] = try removeOwnedFixtureDirectory(directory)
        trace?.record("cycle-cleanup.end")
        try require(ownedDirectoryIsAbsent(directory), "Cycle directory cleanup was not independently confirmed")
        report["temporaryFilesRemaining"] = 0
        trace?.record("memory-settle.begin")
        try await Task.sleep(nanoseconds: 300_000_000)
        trace?.record("memory-settle.end")
        sampler.stop()
        let memory = sampler.snapshot(), settled = GIFResourceMemoryReading.current()
        try require(memory.residentSampleCount > 0, "No valid RSS sample was collected during the recording cycle")
        report["sampledMemory"] = try object(memory)
        report["settledMemory"] = try object(settled)
        report["elapsedSeconds"] = ProcessInfo.processInfo.systemUptime - started
        trace?.record("cycle.end", details: ["elapsedSeconds": ProcessInfo.processInfo.systemUptime - started])
        return CycleResult(report: report, settled: settled, memory: memory)
    }

    private static func pipeline(directory: URL, profile: Profile, witnessDirectory: URL?, sampler: GIFResourceMemorySampler,
                                 probe: RecordingCompositionSmokeReleaseProbe, deadline: Double,
                                 trace: RecordingCompositionSmokeTrace?) async throws -> [String: Any] {
        trace?.record("synthetic-inputs.begin")
        let size = CGSize(width: profile.width, height: profile.height)
        let state = RecordingCompositionState()
        let controller = RecordingOverlayController(state: state), token = UUID(), clock = RecordingCompositionSmokeClock(100)
        state.setCanvasSize(size); state.setCameraSession(token)
        state.setLayout(RecordingCameraLayout(frame: CGRect(x: 0.05, y: 0.12, width: 0.24, height: 0.32), mirrored: false))
        let imageContext = CIContext(options: [.cacheIntermediates: false, .useSoftwareRenderer: true])
        let desktop = try makeDesktop(profile: profile, context: imageContext)
        state.receiveCamera(try makeCamera(profile: profile, context: imageContext), token: token)
        trace?.record("compositor-init.begin")
        let compositor = try RecordingFrameCompositor(size: size, state: state)
        compositor.smokeDiagnosticsEnabled = trace != nil
        trace?.record("writer-init.begin")
        let stops = RecordingCompositionSmokeStops()
        let writer = try RecordingWriter(size: size,
            options: RecordingOptions(frameRate: profile.frameRate, maximumDuration: 10, maximumFileSize: 16 * 1_024 * 1_024),
            outputDirectory: directory, compositor: compositor, automaticallyRefreshOverlays: false,
            clock: { clock.now }, requestStop: { stops.record($0) })
        trace?.record("writer-init.end", details: writer.queue.sync { writer.smokeDiagnosticSnapshot() })
        probe.writer = writer; probe.compositor = compositor; probe.state = state; probe.controller = controller
        defer { controller.hide(); state.setCameraSession(nil); _ = state.setAnnotations([]) }
        do {
            for frame in 0..<2 {
                clock.set(100 + Double(frame) / 10)
                let sample = try makeSample(pixels: desktop, at: 100 + Double(frame) / 10)
                try await append(sample, writer: writer, stops: stops, sampler: sampler, deadline: deadline,
                                 phase: "append-screen-\(frame)", trace: trace)
            }
            // Direct controller interaction, no NSEvent/CGEvent or NSWindow.
            controller.cameraEditing = true
            controller.begin(at: point(0.17, 0.28, size), resizeCamera: false)
            controller.end(at: point(0.52, 0.38, size))
            controller.begin(at: point(0.64, 0.22, size), resizeCamera: true)
            controller.end(at: point(0.70, 0.14, size))
            controller.cancelInteraction()
            var layout = state.snapshot().cameraLayout
            try require(abs(layout.frame.minX - 0.4) < 0.0001 && abs(layout.frame.minY - 0.14) < 0.0001 &&
                        abs(layout.frame.width - 0.3) < 0.0001 && abs(layout.frame.height - 0.4) < 0.0001,
                        "Production camera drag/resize geometry differs")
            layout.mirrored = true; state.setLayout(layout)
            clock.set(100.2); try await refresh(writer, stops: stops, sampler: sampler, deadline: deadline,
                                               phase: "refresh-drag-resize-mirror", trace: trace)
            controller.setCameraCrop(zoom: 2, horizontal: 1, vertical: 1)
            clock.set(100.3); try await refresh(writer, stops: stops, sampler: sampler, deadline: deadline,
                                               phase: "refresh-camera-crop", trace: trace)
            controller.drawing = true; controller.tool = .freehand
            controller.color = NSColor(srgbRed: 0, green: 1, blue: 0, alpha: 1)
            controller.width = max(5, size.width * 0.015)
            controller.begin(at: point(0.1, 0.8, size), resizeCamera: false)
            controller.drag(to: point(0.2, 0.8, size))
            controller.end(at: point(0.28, 0.8, size))
            clock.set(100.4); try await refresh(writer, stops: stops, sampler: sampler, deadline: deadline,
                                               phase: "refresh-live-pen", trace: trace)
            controller.tool = .eraser; controller.width = max(9, size.width * 0.024)
            controller.begin(at: point(0.2, 0.74, size), resizeCamera: false)
            controller.end(at: point(0.2, 0.86, size))
            clock.set(100.5); try await refresh(writer, stops: stops, sampler: sampler, deadline: deadline,
                                               phase: "refresh-live-eraser", trace: trace)
            trace?.record("pause.begin")
            clock.set(100.6); _ = try await writer.setPaused(true)
            trace?.record("pause.end")
            state.receiveCamera(try makePixels(width: profile.cameraWidth, height: profile.cameraHeight,
                image: CIImage(color: CIColor(red: 0, green: 1, blue: 1)), context: imageContext), token: token)
            controller.clear(); controller.cancelInteraction()
            trace?.record("paused-refresh.begin")
            clock.set(101.5); writer.queue.sync { writer.refreshOverlay() }
            try require(writer.queue.sync { writer.needsOverlayRefresh }, "Paused overlay changes were consumed")
            trace?.record("paused-refresh.end")
            trace?.record("resume.begin")
            clock.set(101.6); _ = try await writer.setPaused(false)
            trace?.record("resume.end")
            trace?.record("stop-barrier.begin")
            clock.set(101.7); _ = await writer.stopAccepting()
            trace?.record("stop-barrier.end")
            // Mutation after the stop barrier must not replace the cyan camera
            // snapshot used to finalize the pending resume frame at PTS 0.6.
            state.receiveCamera(try makePixels(width: profile.cameraWidth, height: profile.cameraHeight,
                image: CIImage(color: CIColor(red: 1, green: 0, blue: 1)), context: imageContext), token: token)
            state.setCameraSession(nil); controller.hide()
            sampler.sample()
            trace?.record("finish.begin", details: writer.queue.sync { writer.smokeDiagnosticSnapshot() })
            let movie = try await writer.finish()
            trace?.record("finish.end", details: writer.queue.sync { writer.smokeDiagnosticSnapshot() })
            sampler.sample()
            let snapshot = await writer.snapshot()
            try require(snapshot.retainedVideoFrames == 0 && state.snapshot().camera == nil,
                        "Recording cleanup retained a production frame reference or camera slot")
            try require(stops.message == nil, "Production writer requested an unexpected stop: \(stops.message ?? "")")
            let movieBytes = try fileBytes(movie)
            try require(movieBytes > 0 && movieBytes <= 4 * 1_024 * 1_024, "Synthetic MP4 exceeded its evidence budget")
            var result = try await validate(movie: movie, profile: profile, witnessDirectory: witnessDirectory,
                                            context: imageContext, sampler: sampler, deadline: deadline, trace: trace)
            if let witnessDirectory {
                let destination = witnessDirectory.appendingPathComponent("recording-composition.mp4")
                try FileManager.default.copyItem(at: movie, to: destination)
                result["witnessMovieBytes"] = try fileBytes(destination)
            }
            result["movieBytes"] = movieBytes
            result["writerRetainedFrameReferencesAtFinish"] = snapshot.retainedVideoFrames
            result["cameraSlotsAtCleanup"] = state.snapshot().camera == nil ? 0 : 1
            result["controllersCreated"] = 1
            result["screenSamplesSubmitted"] = 2
            result["staticScreenRefreshes"] = 4
            result["postStopMutationExcluded"] = true
            result["status"] = "passed"
            return result
        } catch {
            // This is only teardown inside the fixture-owned synthetic root,
            // which the caller removes explicitly. It proves no preservation.
            trace?.record("pipeline.failure", details: ["error": String(error.localizedDescription.prefix(512)), "taskCancelled": Task.isCancelled,
                "writer": writer.queue.sync { writer.smokeDiagnosticSnapshot() }])
            trace?.record("discard.begin")
            do {
                try await writer.discard()
                trace?.record("discard.end", details: writer.queue.sync { writer.smokeDiagnosticSnapshot() })
            } catch {
                trace?.record("discard.failure", details: ["error": String(error.localizedDescription.prefix(512)),
                    "writer": writer.queue.sync { writer.smokeDiagnosticSnapshot() }])
            }
            throw error
        }
    }

    private static func validate(movie: URL, profile: Profile, witnessDirectory: URL?, context: CIContext,
                                 sampler: GIFResourceMemorySampler, deadline: Double,
                                 trace: RecordingCompositionSmokeTrace?) async throws -> [String: Any] {
        trace?.record("asset-load.begin")
        let asset = AVURLAsset(url: movie)
        let videoTracks = try await asset.loadTracks(withMediaType: .video)
        let audioTracks = try await asset.loadTracks(withMediaType: .audio)
        try require(videoTracks.count == 1 && audioTracks.isEmpty, "Unexpected synthetic MP4 track count")
        let formats = try await videoTracks[0].load(.formatDescriptions)
        try require(!formats.isEmpty && formats.allSatisfy { CMFormatDescriptionGetMediaSubType($0) == kCMVideoCodecType_H264 },
                    "Synthetic recording did not contain H.264 video")
        let colorProperties: [[String: String]] = formats.map { format in
            ["primaries": CMFormatDescriptionGetExtension(format, extensionKey: kCMFormatDescriptionExtension_ColorPrimaries) as? String ?? "missing",
             "transfer": CMFormatDescriptionGetExtension(format, extensionKey: kCMFormatDescriptionExtension_TransferFunction) as? String ?? "missing",
             "matrix": CMFormatDescriptionGetExtension(format, extensionKey: kCMFormatDescriptionExtension_YCbCrMatrix) as? String ?? "missing"]
        }
        try require(colorProperties.allSatisfy {
            $0["primaries"] == (kCMFormatDescriptionColorPrimaries_ITU_R_709_2 as String) &&
            $0["transfer"] == (kCMFormatDescriptionTransferFunction_ITU_R_709_2 as String) &&
            $0["matrix"] == (kCMFormatDescriptionYCbCrMatrix_ITU_R_709_2 as String)
        }, "Encoded MP4 color declarations differ from the writer Rec.709 output contract: \(colorProperties)")
        let duration = try await asset.load(.duration).seconds
        try require(abs(duration - profile.duration) < 0.02, "Pause removal or final MP4 duration differs")
        trace?.record("asset-load.end")
        trace?.record("stored-packets.begin")
        let stored = try storedTiming(asset: asset, track: videoTracks[0], profile: profile)
        trace?.record("stored-packets.end")
        trace?.record("decode.begin")
        let reader = try AVAssetReader(asset: asset)
        defer { if reader.status == .reading { reader.cancelReading() } }
        let output = AVAssetReaderTrackOutput(track: videoTracks[0], outputSettings:
            [kCVPixelBufferPixelFormatTypeKey as String: kCVPixelFormatType_32BGRA])
        try require(reader.canAdd(output), "Synthetic MP4 decoder unavailable")
        reader.add(output); try require(reader.startReading(), "Synthetic MP4 decoder failed to start")
        var frames = 0, pixelChecks = 0, pngBytes = 0
        while let sample = output.copyNextSampleBuffer() {
            try checkDeadline(deadline)
            guard CMSampleBufferGetNumSamples(sample) > 0 else { continue }
            let index = frames
            try require(index < profile.encodedFrames, "MP4 decoded more frames than expected")
            guard let pixels = CMSampleBufferGetImageBuffer(sample) else { throw failure("Decoded MP4 has no image buffer") }
            try require(CVPixelBufferGetWidth(pixels) == profile.width && CVPixelBufferGetHeight(pixels) == profile.height,
                        "Decoded recording dimensions differ")
            let timestamp = CMSampleBufferGetPresentationTimeStamp(sample).seconds
            try require(abs(timestamp - Double(index) / 10) < 0.001, "Decoded recording PTS differ")
            try autoreleasepool {
                let image = CIImage(cvPixelBuffer: pixels)
                for check in checks(frame: index) {
                    let observed = color(image, at: point(check.x, check.y, CGSize(width: profile.width, height: profile.height)), context: context)
                    try require(zip(observed, check.rgb).allSatisfy { abs($0.0 - $0.1) <= check.tolerance },
                        "Decoded frame \(index) failed \(check.label): \(observed), expected \(check.rgb)")
                    pixelChecks += 1
                }
                if index == 4, let witnessDirectory {
                    let destination = witnessDirectory.appendingPathComponent("recording-composition.png")
                    guard let image = context.createCGImage(image, from: image.extent),
                          let writer = CGImageDestinationCreateWithURL(destination as CFURL, UTType.png.identifier as CFString, 1, nil)
                    else { throw failure("Decoded PNG witness could not be created") }
                    CGImageDestinationAddImage(writer, image, nil)
                    try require(CGImageDestinationFinalize(writer), "Decoded PNG witness could not be finalized")
                    pngBytes = try fileBytes(destination)
                    try require(pngBytes > 0 && pngBytes <= 4 * 1_024 * 1_024, "Decoded PNG exceeded its evidence budget")
                }
            }
            frames += 1; sampler.sample()
        }
        try require(reader.status == .completed && frames == profile.encodedFrames,
                    "Decoded MP4 did not finish with exactly seven frames: \(reader.error?.localizedDescription ?? "")")
        trace?.record("decode.end", details: ["decodedFrames": frames, "decodedPixelChecks": pixelChecks])
        return ["decodedFrames": frames, "decodedPixelChecks": pixelChecks, "durationSeconds": duration, "videoCodec": "H.264",
                "storedPacketTiming": stored, "encodedColorProperties": colorProperties, "witnessPNGBytes": pngBytes,
                "verifiedPhases": ["initial-camera-quadrants", "drag-resize-mirror", "camera-crop",
                    "live-pen", "live-eraser", "static-screen-updates", "pause-removal", "frozen-stop-cyan-camera", "sRGB-gray-color-ramp-through-Rec709"]]
    }

    private static func storedTiming(asset: AVAsset, track: AVAssetTrack, profile: Profile) throws -> [String: Any] {
        let reader = try AVAssetReader(asset: asset)
        defer { if reader.status == .reading { reader.cancelReading() } }
        let output = AVAssetReaderTrackOutput(track: track, outputSettings: nil)
        try require(reader.canAdd(output), "Stored MP4 packet reader unavailable")
        reader.add(output); try require(reader.startReading(), "Stored packet reader failed")
        var count = 0, end = CMTime.zero
        while let sample = output.copyNextSampleBuffer() {
            guard CMSampleBufferGetNumSamples(sample) > 0 else { continue }
            let pts = CMSampleBufferGetPresentationTimeStamp(sample), duration = CMSampleBufferGetDuration(sample)
            try require(pts.isNumeric && duration.isNumeric && duration.seconds > 0 && CMTimeCompare(pts, end) == 0,
                        "Stored MP4 packets are not positive-duration and adjacent")
            end = CMTimeAdd(pts, duration); count += CMSampleBufferGetNumSamples(sample)
            try require(count <= profile.encodedFrames, "Stored MP4 packet count exceeded the fixture bound")
        }
        try require(reader.status == .completed && count == profile.encodedFrames && abs(end.seconds - profile.duration) < 0.02,
                    "Stored MP4 packet endpoint/count differs")
        return ["packets": count, "adjacent": true, "positiveDurations": true, "endSeconds": end.seconds]
    }

    private struct PixelCheck {
        let label: String
        let x: CGFloat
        let y: CGFloat
        let rgb: [Int]
        var tolerance = 45
    }
    private static let rampColors = [[32, 32, 32], [64, 64, 64], [128, 128, 128], [192, 192, 192],
        [224, 224, 224], [48, 96, 176], [176, 80, 48], [64, 176, 112]]
    private static func checks(frame: Int) -> [PixelCheck] {
        let navy = [20, 30, 90], dark = [40, 40, 40]
        var result = [PixelCheck(label: "untouched-upper-desktop", x: 0.9, y: 0.85, rgb: navy),
                      PixelCheck(label: "untouched-lower-desktop", x: 0.9, y: 0.05, rgb: dark)]
        for (index, rgb) in rampColors.enumerated() {
            result.append(PixelCheck(label: "sRGB-gray-color-ramp-\(index)",
                x: (CGFloat(index) + 0.5) / CGFloat(rampColors.count), y: 0.96, rgb: rgb, tolerance: 12))
        }
        if frame < 2 {
            result += [PixelCheck(label: "camera-lower-left-red", x: 0.11, y: 0.20, rgb: [255, 0, 0]),
                       PixelCheck(label: "camera-lower-right-green", x: 0.23, y: 0.20, rgb: [0, 255, 0]),
                       PixelCheck(label: "camera-upper-left-blue", x: 0.11, y: 0.36, rgb: [0, 0, 255]),
                       PixelCheck(label: "camera-upper-right-yellow", x: 0.23, y: 0.36, rgb: [255, 255, 0])]
        } else {
            result.append(PixelCheck(label: "old-camera-position-cleared", x: 0.11, y: 0.20, rgb: dark))
            if frame == 2 {
                result += [PixelCheck(label: "moved-mirrored-lower-left", x: 0.475, y: 0.24, rgb: [0, 255, 0]),
                           PixelCheck(label: "moved-mirrored-lower-right", x: 0.625, y: 0.24, rgb: [255, 0, 0]),
                           PixelCheck(label: "moved-mirrored-upper-left", x: 0.475, y: 0.44, rgb: [255, 255, 0]),
                           PixelCheck(label: "moved-mirrored-upper-right", x: 0.625, y: 0.44, rgb: [0, 0, 255])]
            } else {
                result.append(PixelCheck(label: frame == 6 ? "frozen-stop-camera-cyan" : "cropped-camera-yellow",
                    x: 0.55, y: 0.34, rgb: frame == 6 ? [0, 255, 255] : [255, 255, 0]))
            }
        }
        if frame == 4 { result.append(PixelCheck(label: "pen-is-in-output", x: 0.2, y: 0.8, rgb: [0, 255, 0])) }
        if frame == 5 {
            result.append(PixelCheck(label: "eraser-reveals-desktop", x: 0.2, y: 0.8, rgb: navy))
            result.append(PixelCheck(label: "eraser-preserves-other-stroke", x: 0.12, y: 0.8, rgb: [0, 255, 0]))
        }
        if frame == 6 { result.append(PixelCheck(label: "pause-clear-applied-at-resume", x: 0.12, y: 0.8, rgb: navy)) }
        return result
    }

    private static func makeDesktop(profile: Profile, context: CIContext) throws -> CVPixelBuffer {
        let lower = CIImage(color: CIColor(cgColor: CGColor(srgbRed: 40.0 / 255, green: 40.0 / 255, blue: 40.0 / 255, alpha: 1)))
            .cropped(to: CGRect(x: 0, y: 0, width: profile.width, height: profile.height / 2))
        let upper = CIImage(color: CIColor(cgColor: CGColor(srgbRed: 20.0 / 255, green: 30.0 / 255, blue: 90.0 / 255, alpha: 1)))
            .cropped(to: CGRect(x: 0, y: profile.height / 2, width: profile.width, height: profile.height / 2))
        var image = lower.composited(over: upper)
        for (index, rgb) in rampColors.enumerated() {
            let color = CGColor(srgbRed: CGFloat(rgb[0]) / 255, green: CGFloat(rgb[1]) / 255,
                                blue: CGFloat(rgb[2]) / 255, alpha: 1)
            let stripe = CGRect(x: CGFloat(index * profile.width) / CGFloat(rampColors.count),
                y: CGFloat(profile.height) * 0.92, width: CGFloat(profile.width) / CGFloat(rampColors.count),
                height: CGFloat(profile.height) * 0.08)
            image = CIImage(color: CIColor(cgColor: color)).cropped(to: stripe).composited(over: image)
        }
        return try makePixels(width: profile.width, height: profile.height, image: image, context: context)
    }

    private static func makeCamera(profile: Profile, context: CIContext) throws -> CVPixelBuffer {
        var image = CIImage.empty()
        let colors = [CIColor(red: 1, green: 0, blue: 0), CIColor(red: 0, green: 1, blue: 0),
                      CIColor(red: 0, green: 0, blue: 1), CIColor(red: 1, green: 1, blue: 0)]
        for index in 0..<4 {
            let rect = CGRect(x: (index % 2) * profile.cameraWidth / 2, y: (index / 2) * profile.cameraHeight / 2,
                              width: profile.cameraWidth / 2, height: profile.cameraHeight / 2)
            image = CIImage(color: colors[index]).cropped(to: rect).composited(over: image)
        }
        return try makePixels(width: profile.cameraWidth, height: profile.cameraHeight, image: image, context: context)
    }

    private static func makePixels(width: Int, height: Int, image: CIImage, context: CIContext) throws -> CVPixelBuffer {
        var output: CVPixelBuffer?
        let attributes = [kCVPixelBufferCGImageCompatibilityKey as String: true,
                          kCVPixelBufferCGBitmapContextCompatibilityKey as String: true] as CFDictionary
        guard CVPixelBufferCreate(kCFAllocatorDefault, width, height, kCVPixelFormatType_32BGRA, attributes, &output) == kCVReturnSuccess,
              let output else { throw failure("Could not allocate bounded synthetic pixels") }
        let bounds = CGRect(x: 0, y: 0, width: width, height: height)
        let srgb = CGColorSpace(name: CGColorSpace.sRGB)!
        context.render(image.cropped(to: bounds), to: output, bounds: bounds, colorSpace: srgb)
        CVBufferSetAttachment(output, kCVImageBufferCGColorSpaceKey, srgb, .shouldPropagate)
        CVBufferSetAttachment(output, kCVImageBufferColorPrimariesKey, kCVImageBufferColorPrimaries_ITU_R_709_2, .shouldPropagate)
        CVBufferSetAttachment(output, kCVImageBufferTransferFunctionKey, kCVImageBufferTransferFunction_sRGB, .shouldPropagate)
        return output
    }

    private static func makeSample(pixels: CVPixelBuffer, at seconds: Double) throws -> CMSampleBuffer {
        var format: CMVideoFormatDescription?
        guard CMVideoFormatDescriptionCreateForImageBuffer(allocator: kCFAllocatorDefault, imageBuffer: pixels,
            formatDescriptionOut: &format) == noErr, let format else { throw failure("Synthetic video format failed") }
        var timing = CMSampleTimingInfo(duration: CMTime(value: 1, timescale: 10),
            presentationTimeStamp: CMTime(seconds: seconds, preferredTimescale: 48_000), decodeTimeStamp: .invalid)
        var result: CMSampleBuffer?
        guard CMSampleBufferCreateReadyWithImageBuffer(allocator: kCFAllocatorDefault, imageBuffer: pixels,
            formatDescription: format, sampleTiming: &timing, sampleBufferOut: &result) == noErr, let result,
              let attachments = CMSampleBufferGetSampleAttachmentsArray(result, createIfNecessary: true)
        else { throw failure("Synthetic video sample failed") }
        let attachment = unsafeBitCast(CFArrayGetValueAtIndex(attachments, 0), to: NSMutableDictionary.self)
        attachment[SCStreamFrameInfo.status.rawValue] = SCFrameStatus.complete.rawValue
        return result
    }

    private static func append(_ sample: CMSampleBuffer, writer: RecordingWriter, stops: RecordingCompositionSmokeStops,
                               sampler: GIFResourceMemorySampler, deadline: Double, phase: String,
                               trace: RecordingCompositionSmokeTrace?) async throws {
        let boundary = min(deadline, ProcessInfo.processInfo.systemUptime + 10)
        trace?.record(phase + ".begin", details: ["limitSeconds": 10, "effectiveBudgetSeconds": max(0, boundary - ProcessInfo.processInfo.systemUptime),
            "globalDeadlineRemainingSeconds": max(0, deadline - ProcessInfo.processInfo.systemUptime), "writer": writer.queue.sync { writer.smokeDiagnosticSnapshot() }])
        var attempts = 0, maximumAttemptSeconds = 0.0
        do {
            while true {
                let began = ProcessInfo.processInfo.systemUptime
                let accepted = writer.queue.sync { writer.consume(sample, of: .screen) }
                attempts += 1; maximumAttemptSeconds = max(maximumAttemptSeconds, ProcessInfo.processInfo.systemUptime - began)
                if accepted { break }
                try require(stops.message == nil, "Encoder stopped while appending synthetic screen: \(stops.message ?? "")")
                try checkDeadline(boundary); try await Task.sleep(nanoseconds: 1_000_000)
            }
        } catch {
            trace?.record(phase + ".failure", details: ["error": String(error.localizedDescription.prefix(512)), "attempts": attempts,
                "maximumAttemptSeconds": maximumAttemptSeconds, "deadlineOverrunSeconds": max(0, ProcessInfo.processInfo.systemUptime - boundary),
                "writer": writer.queue.sync { writer.smokeDiagnosticSnapshot() }])
            throw error
        }
        trace?.record(phase + ".end", details: ["attempts": attempts, "maximumAttemptSeconds": maximumAttemptSeconds])
        sampler.sample()
    }

    private static func refresh(_ writer: RecordingWriter, stops: RecordingCompositionSmokeStops,
                                sampler: GIFResourceMemorySampler, deadline: Double, phase: String,
                                trace: RecordingCompositionSmokeTrace?) async throws {
        let boundary = min(deadline, ProcessInfo.processInfo.systemUptime + 10)
        trace?.record(phase + ".begin", details: ["limitSeconds": 10, "effectiveBudgetSeconds": max(0, boundary - ProcessInfo.processInfo.systemUptime),
            "globalDeadlineRemainingSeconds": max(0, deadline - ProcessInfo.processInfo.systemUptime), "writer": writer.queue.sync { writer.smokeDiagnosticSnapshot() }])
        var attempts = 0, maximumAttemptSeconds = 0.0
        do {
            while writer.queue.sync(execute: { writer.needsOverlayRefresh }) {
                let began = ProcessInfo.processInfo.systemUptime
                writer.queue.sync { writer.refreshOverlay() }
                attempts += 1; maximumAttemptSeconds = max(maximumAttemptSeconds, ProcessInfo.processInfo.systemUptime - began)
                try require(stops.message == nil, "Encoder stopped during static-screen refresh: \(stops.message ?? "")")
                // Preserve the original check, including after an accepted refresh.
                try checkDeadline(boundary); try await Task.sleep(nanoseconds: 1_000_000)
            }
        } catch {
            trace?.record(phase + ".failure", details: ["error": String(error.localizedDescription.prefix(512)), "attempts": attempts,
                "maximumAttemptSeconds": maximumAttemptSeconds, "deadlineOverrunSeconds": max(0, ProcessInfo.processInfo.systemUptime - boundary),
                "writer": writer.queue.sync { writer.smokeDiagnosticSnapshot() }])
            throw error
        }
        trace?.record(phase + ".end", details: ["attempts": attempts, "maximumAttemptSeconds": maximumAttemptSeconds])
        sampler.sample()
    }

    private static func color(_ image: CIImage, at point: CGPoint, context: CIContext) -> [Int] {
        var bytes = [UInt8](repeating: 0, count: 4)
        bytes.withUnsafeMutableBytes {
            context.render(image, toBitmap: $0.baseAddress!, rowBytes: 4,
                bounds: CGRect(x: floor(point.x), y: floor(point.y), width: 1, height: 1),
                format: .RGBA8, colorSpace: CGColorSpace(name: CGColorSpace.sRGB)!)
        }
        return bytes.prefix(3).map(Int.init)
    }
    private static func point(_ x: CGFloat, _ y: CGFloat, _ size: CGSize) -> CGPoint { CGPoint(x: x * size.width, y: y * size.height) }
    /// Every cycle directory was already removed and independently checked.
    /// Require the root to be empty: rmdir cannot silently delete a leftover
    /// descendant, and avoids Foundation's recursive removal on an empty root.
    static func removeOwnedEmptyRoot(_ url: URL) throws -> String {
        if rmdir(url.path) == 0 {
            try require(ownedDirectoryIsAbsent(url), "Empty fixture root remained after rmdir")
            return "empty-root-rmdir-and-lstat-confirmed"
        }
        let code = errno
        if code == ENOENT, ownedDirectoryIsAbsent(url) { return "empty-root-already-absent-lstat-confirmed" }
        let entries = (try? FileManager.default.contentsOfDirectory(atPath: url.path)) ?? []
        throw failure("Empty fixture root cleanup failed: errno=\(code), rootAbsent=\(ownedDirectoryIsAbsent(url)), entries=\(Array(entries.prefix(16)))")
    }

    /// Cleanup of this fixture's unique owned paths is idempotent, but a
    /// missing descendant or inaccessible path is not proof the root is gone.
    /// The independent lstat must report ENOENT for this exact entire directory.
    static func removeOwnedFixtureDirectory(_ url: URL,
        remover: (URL) throws -> Void = { try FileManager.default.removeItem(at: $0) }) throws -> String {
        do { try remover(url) }
        catch {
            let error = error as NSError
            let missing = (error.domain == NSCocoaErrorDomain && error.code == CocoaError.fileNoSuchFile.rawValue) ||
                (error.domain == NSPOSIXErrorDomain && error.code == Int(ENOENT))
            guard missing, ownedDirectoryIsAbsent(url) else { throw error }
            return "already-absent-confirmed-by-lstat"
        }
        try require(ownedDirectoryIsAbsent(url), "Owned directory still exists after removal")
        return "removed-and-absence-confirmed-by-lstat"
    }

    private static func ownedDirectoryIsAbsent(_ url: URL) -> Bool {
        var information = stat()
        return lstat(url.path, &information) != 0 && errno == ENOENT
    }

    private static func fileBytes(_ url: URL) throws -> Int {
        guard let result = try url.resourceValues(forKeys: [.fileSizeKey]).fileSize else { throw failure("Evidence file size unavailable") }
        return result
    }
    private static func checkDeadline(_ deadline: Double) throws {
        try Task.checkCancellation()
        try require(ProcessInfo.processInfo.systemUptime < deadline, "Recording smoke exceeded its cooperative deadline")
    }
    private static func object<T: Encodable>(_ value: T) throws -> [String: Any] {
        guard let result = try JSONSerialization.jsonObject(with: JSONEncoder().encode(value)) as? [String: Any]
        else { throw failure("Evidence value is not a JSON object") }
        return result
    }
    private static func write(_ report: [String: Any], to url: URL) throws {
        let data = try JSONSerialization.data(withJSONObject: report, options: [.prettyPrinted, .sortedKeys])
        try require(data.count <= 128 * 1_024, "Recording smoke JSON exceeded its evidence budget")
        try data.write(to: url, options: .atomic)
    }
    private static func require(_ condition: Bool, _ message: String) throws { if !condition { throw failure(message) } }
    private static func failure(_ message: String) -> NSError {
        NSError(domain: "PicShot.RecordingCompositionSmoke", code: 1, userInfo: [NSLocalizedDescriptionKey: message])
    }
}

@MainActor
private final class RecordingCompositionSmokeReleaseProbe {
    weak var writer: RecordingWriter?
    weak var compositor: RecordingFrameCompositor?
    weak var state: RecordingCompositionState?
    weak var controller: RecordingOverlayController?
    var liveObjects: [String: Bool] { ["writer": writer != nil, "compositor": compositor != nil,
                                      "state": state != nil, "overlayController": controller != nil] }
    var liveObjectCount: Int { [writer != nil, compositor != nil, state != nil, controller != nil].filter { $0 }.count }
}

private final class RecordingCompositionSmokeClock: @unchecked Sendable {
    private let lock = NSLock()
    private var time: CMTime
    init(_ seconds: Double) { time = CMTime(seconds: seconds, preferredTimescale: 48_000) }
    var now: CMTime { lock.lock(); defer { lock.unlock() }; return time }
    func set(_ seconds: Double) { lock.lock(); defer { lock.unlock() }; time = CMTime(seconds: seconds, preferredTimescale: 48_000) }
}

private final class RecordingCompositionSmokeStops: @unchecked Sendable {
    private let lock = NSLock()
    private var stored: String?
    var message: String? { lock.lock(); defer { lock.unlock() }; return stored }
    func record(_ message: String?) { lock.lock(); defer { lock.unlock() }; if stored == nil { stored = message ?? "automatic limit" } }
}

/// Only explicit diagnostic runs write this sidecar. Keep no media references,
/// sample only at phase boundaries (never every poll), and preserve the first
/// failure before discard/root-cleanup can change the current phase or writer.
@MainActor
final class RecordingCompositionSmokeTrace {
    static let maximumEvents = 192
    static let maximumBytes = 128 * 1_024
    private let url: URL
    private let started = ProcessInfo.processInfo.systemUptime
    private var previous = ProcessInfo.processInfo.systemUptime
    private var previousEvent = "none"
    private var events: [[String: Any]] = []
    private var droppedEvents = 0
    private var firstFailure: [String: Any]?
    private var lastWriteError: String?
    var cycle = "setup"

    init(directory: URL) { url = directory.appendingPathComponent("recording-composition-trace.json") }

    var summary: [String: Any] {
        var result: [String: Any] = ["file": url.lastPathComponent, "events": events.count,
            "droppedEvents": droppedEvents, "maximumEvents": Self.maximumEvents,
            "maximumBytes": Self.maximumBytes, "observationalOnly": true, "diagnosticOverlay": "recording-wait-trace-v1",
            "timingScope": "monotonic phase boundaries; synchronous calls cannot be interrupted by the cooperative deadline"]
        if let firstFailure { result["firstFailure"] = firstFailure }
        if let lastWriteError { result["lastWriteError"] = lastWriteError }
        return result
    }

    func record(_ event: String, details: [String: Any] = [:]) {
        let now = ProcessInfo.processInfo.systemUptime
        let entry: [String: Any] = ["event": event, "previousEvent": previousEvent, "cycle": cycle,
            "elapsedSeconds": now - started, "sincePreviousEventSeconds": now - previous,
            "details": details]
        previous = now; previousEvent = event
        if event.hasSuffix(".failure"), firstFailure == nil { firstFailure = entry }
        events.append(entry)
        while events.count > Self.maximumEvents { events.removeFirst(); droppedEvents += 1 }
        do {
            while true {
                var report = summary
                report["schemaVersion"] = 1
                report["sourceCommit"] = Bundle.main.infoDictionary?["PicShotSourceCommit"] as? String ?? "unknown"
                report["events"] = events
                let data = try JSONSerialization.data(withJSONObject: report, options: [.sortedKeys])
                if data.count <= Self.maximumBytes {
                    try data.write(to: url, options: .atomic)
                    return
                }
                guard events.count > 1 else {
                    throw NSError(domain: "PicShot.RecordingCompositionSmokeTrace", code: 1,
                        userInfo: [NSLocalizedDescriptionKey: "Diagnostic event exceeded its fixed byte budget"])
                }
                events.removeFirst(); droppedEvents += 1
            }
        } catch {
            lastWriteError = String(error.localizedDescription.prefix(512))
            // Evidence failure must be visible, but must not mask/replace the
            // original pipeline failure or change an existing gate's outcome.
            fputs("Recording diagnostic write failed: \(lastWriteError!)\n", stderr)
        }
    }
}
