#!/usr/bin/env python3
"""Regenerate original barcode module vectors with already installed ReportLab 4.4.9.
No downloads; no copied barcode artwork. Native Apple CoreImage makes the other formats.
Run from any directory. Generated data and generator provenance are committed as Swift
so both XCTest and the packaged native acceptance fixture use exactly the same vectors.
"""
from pathlib import Path
import hashlib
import importlib.metadata
from reportlab.graphics.barcode import code39, eanbc, ecc200datamatrix
from reportlab.graphics.shapes import Rect
import reportlab

assert reportlab.Version == "4.4.9", "Use the reviewed generator version, ReportLab 4.4.9"

def linear(widget):
    bars = [shape for shape in widget.draw().contents if isinstance(shape, Rect) and shape.fillColor is not None]
    # UPCA.widget.width underreports with quiet=0 in 4.4.9. Use actual drawn extent.
    rows = [0] * round(max(shape.x + shape.width for shape in bars))
    for shape in bars:
        for x in range(round(shape.x), round(shape.x + shape.width)):
            rows[x] = 1
    return ''.join(map(str, rows))

code = code39.Standard39('PICSHOT39', checksum=0, barWidth=1, ratio=3, gap=1, quiet=0)
code.validate(); code.encode(); pattern = code.decompose()
# Match ReportLab Barcode.draw: b/B = bars, s/S = spaces, uppercase = wide.
widths = {'b': 1, 's': 1, 'B': 3, 'S': 3, 'i': 1}
codebits = ''.join(('1' if char in 'bB' else '0') * widths[char] for char in pattern)
matrix = ecc200datamatrix.ECC200DataMatrix('PICSHOTDM123')
matrix.validate(); dm = [''.join(map(str,row)) for row in matrix.encode()]
ean = eanbc.Ean13BarcodeWidget('590123412345',barWidth=1,humanReadable=0,quiet=0)
upc = eanbc.UPCA('01234567890',barWidth=1,humanReadable=0,quiet=0)
# EAN-13 leading 0 is physically identical to UPC-A. Prove equality independently
# through two native ReportLab classes; Vision preserves its native 13-digit result.
equivalent = eanbc.Ean13BarcodeWidget('001234567890',barWidth=1,humanReadable=0,quiet=0)
assert linear(upc) == linear(equivalent)
assert ean.value + ean._checkdigit(ean.value) == '5901234123457'
assert upc.value + upc._checkdigit(upc.value) == '012345678905'
assert len(linear(ean)) == 95 and len(dm) == 44 and all(len(row)==44 for row in dm)
license_text = importlib.metadata.distribution('reportlab').read_text('licenses/LICENSE')
assert license_text
license_text = '\n'.join(line.rstrip() for line in license_text.splitlines())
vectors={'ean13':[linear(ean)], 'upca':[linear(upc)], 'code39':[codebits], 'dataMatrix':dm}
output = ['// Generated by scripts/Barcode/generate-vectors.py using ReportLab 4.4.9.',
'// Original fixture payloads. No external image, font, or copied source is embedded.',
'// Generator: https://docs.reportlab.com/reportlab/barcode/',
'// Source: https://hg.reportlab.com/hg-public/reportlab/',
'// Data Matrix is the generator\'s 44x44 ECC200 C40 Type 12 variant.',
'// Rows are bottom-to-top, matching CoreGraphics and ReportLab.',
'// The macOS acceptance run is the independent Apple Vision decoder verification.',
'// Until that run passes, these are generated test inputs, not verified decode results.',
'/* Generator license (ReportLab toolkit; generator code is not redistributed):',license_text,'*/',
'enum BarcodeModuleVectors {']
for name,rows in vectors.items():
    digest=hashlib.sha256(('\n'.join(rows)).encode()).hexdigest()
    output.append(f'    // SHA-256 (rows joined by LF, no trailing LF): {digest}')
    output.append(f'    static let {name}: [String] = [')
    output += [f'        "{row}",' for row in rows]
    output.append('    ]')
output.append('}')
root=Path(__file__).resolve().parents[2]
path=root/'Sources/PicShot/BarcodeModuleVectors.swift'
path.write_text('\n'.join(output)+'\n')
print(path)
